<!-- app/views/index.phtml -->
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
div#container{width:95%}
div#header {background-color:#99bbbb;text-align:center;}
div#menu {background-color:#ffff99; height:900px; width:15%; float:left;}
div#content {background-color:#EEEEEE; height:900px; width:85%; float:left;}
div#footer {background-color:#99bbbb; clear:both; text-align:center;}
h1 {margin-bottom:0;}
h2 {margin-bottom:0; font-size:14px;}
ul {margin:0;}
li {list-style:none;}
</style>
</head>

<body>

<div id="container">

<div id="header">
<h1>Wish</h1>
</div>

<div id="menu">
<?php 
echo $this->elements->getMenu();
?>
</div>

<div id="content">
<?php echo $this->getContent() ?>
</div>

<div id="footer">Copyright flosers.com.cn</div>

</div>

</body>
</html>
